import {
  MDBBox,
  MDBBtn,
  MDBCardImage,
  MDBCol,
  MDBContainer,
  MDBRow,
  MDBTypography,
  MDBView,
} from "mdbreact";
import React from "react";
import { makeStyles, Typography } from "@material-ui/core";
import img124 from "./eclassImg/shmw124.jpg";
import { useHistory } from "react-router-dom";

const useStyles = makeStyles(() => ({
  bg124: {
    width: "100%",
    marginTop: "100px",
    borderRadius: "10px",
  },
  bgbtn: {
    backgroundImage:
      "https://alldrawings.ams3.digitaloceanspaces.com/media_autogenerated/items_info_main_image/old/blue/Cars/Mercedes-Benz_E500_W124_1994.gif",
  },
  backgnd: {
    // backgroundImage:
  },
  img124: {
    width: "100px",
  },
  w124: {
    width: "100%",
    marginTop: "50px",
    borderRadius: "10px",
  },
  btn: {
    position: "absolute",
    top: "1310px",
    left: "47%",
    transform: "translate(-50%, -50%)",
    backgroundColor: "black",
    color: "white",
    fontSize: "20px",
    cursor: "pointer",
    borderRadius: "10px",
    fontFamily: "Nunito",
  },
  btn2: {
    position: "absolute",
    top: "1150px",
    left: "60%",
    transform: "translate(-50%, -50%)",
    backgroundColor: "black",
    color: "white",
    fontSize: "20px",
    cursor: "pointer",
    borderRadius: "10px",
    fontFamily: "Nunito",
  },
  btn3: {
    position: "absolute",
    top: "900px",
    left: "26%",
    transform: "translate(-50%, -50%)",
    backgroundColor: "black",
    color: "white",
    fontSize: "20px",
    cursor: "pointer",
    borderRadius: "10px",
    fontFamily: "Nunito",
  },
  btn4: {
    position: "absolute",
    top: "950px",
    left: "45%",
    transform: "translate(-50%, -50%)",
    backgroundColor: "black",
    color: "white",
    fontSize: "20px",
    cursor: "pointer",
    borderRadius: "10px",
    fontFamily: "Nunito",
  },
  text: {
    color: "white",
    fontFamily: "Nunito"
  }
}));

export default function W124() {
  const classes = useStyles();
  const history = useHistory();


  return (
    <MDBContainer>
      <img
        className={classes.bg124}
        src="https://wallpapercave.com/wp/wp2461245.jpg"
      ></img>
      <Typography className={classes.text}>
        Mercedes-Benz W124 — серия легковых автомобилей бизнес-класса немецкой
        торговой марки Mercedes-Benz, которая производилась в 1984—1996 годах.
        Впервые была представлена в 1984 году и предназначалась для замены
        моделей серии W123. В 1995 году автомобили W124 с кузовом седан уступили
        своё место в модельном ряду фирмы Mercedes-Benz следующему поколению
        семейства E-класса W210; автомобили с кузовом универсал (S124)
        оставались на конвейере заводов в Зиндельфингене, Бремене, Раштатте до
        апреля 1996 года.
      </Typography>
      

      <div className={classes.backgnd}>
        <img
          className={classes.w124}
          src="http://3dcar.ru/blueprints/Mercedes/Mercedes_E_W124_1985.jpg"
        ></img>
        <button onClick={() => history.replace("/engine")} className={classes.btn}>Двигатель</button>
        <button className={classes.btn2}>Ходовая часть</button>
        <button className={classes.btn3}>Электрическая часть</button>
        <button className={classes.btn4}>Кузовная часть</button>
      </div>
      <iframe width="100%" height="706" src="https://www.youtube.com/embed/-9VC1PNAHMI" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </MDBContainer>
  );
}
